[project]
name = "payment-aggregator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.118.0",
    "psycopg2-binary>=2.9.10",
    "ruff>=0.13.2",
    "uvicorn>=0.37.0",
]
